# ============================================================
# routes/report.py — AuthentIfy Backend
# Project: AuthentIfy — "Verify before you trust."
# Role   : Report retrieval endpoint — serves previously
#          saved analysis reports by report ID.
#
# Endpoint: GET /report/<report_id>
#
# Reports are JSON files saved to Config.REPORTS_FOLDER by
# routes/analyze.py after each successful analysis run.
# Each report is identified by a UUID hex string generated
# during upload (see utils/file_handler.sanitize_filename).
#
# ALL responses — success AND error — are JSON.
# This endpoint never returns HTML error pages.
# ============================================================

from __future__ import annotations

import re

from flask import Blueprint, jsonify

from utils import file_handler


# ── Blueprint Setup ──────────────────────────────────────────

report_bp = Blueprint(
    "report_bp", __name__, url_prefix="/report"
)


# ── UUID Validation ──────────────────────────────────────────
# Report IDs are generated by uuid.uuid4().hex which produces
# a 32-character lowercase hexadecimal string (no dashes).
# We also accept the standard 8-4-4-4-12 dashed format for
# flexibility.
#
# Examples of valid report IDs:
#   "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6"    (hex, 32 chars)
#   "a1b2c3d4-e5f6-a7b8-c9d0-e1f2a3b4c5d6" (dashed, 36 chars)

_UUID_PATTERN = re.compile(
    r"^[0-9a-fA-F]{32}$"          # 32-char hex (uuid4().hex)
    r"|"
    r"^[0-9a-fA-F]{8}"            # 8 hex digits
    r"-[0-9a-fA-F]{4}"            # - 4 hex digits
    r"-[0-9a-fA-F]{4}"            # - 4 hex digits
    r"-[0-9a-fA-F]{4}"            # - 4 hex digits
    r"-[0-9a-fA-F]{12}$"          # - 12 hex digits
)


def _is_valid_report_id(report_id: str) -> bool:
    """Validate that a report ID is a properly formatted UUID.

    Accepts both 32-char hex strings (as generated by the
    upload handler) and standard dashed UUID format.

    Args:
        report_id: The report ID string to validate.

    Returns:
        True if the ID matches a valid UUID pattern.
    """
    if not report_id or not isinstance(report_id, str):
        return False

    return _UUID_PATTERN.match(report_id) is not None


# ── Route ────────────────────────────────────────────────────


@report_bp.route("/<report_id>", methods=["GET"])
def get_report(report_id: str):
    """GET /report/<report_id> — Retrieve a saved analysis report.

    Validates the report ID format, loads the corresponding
    JSON report from disk, and returns it.  Used by the
    frontend to display previously completed analyses.

    Validation:
        The report_id must be a valid UUID string (32-char
        hex or standard dashed format).  Invalid formats are
        rejected with a 400 before any disk access occurs,
        preventing path traversal and injection attacks.

    Args:
        report_id: UUID hex string identifying the report.

    Returns:
        200: Full report JSON on success.
        400: Invalid report ID format (JSON error).
        404: Report not found (JSON error).
    """
    # ── Step 1: Validate report ID format ────────────────────
    # Reject malformed IDs before touching the filesystem.
    # This guards against path traversal (e.g., "../../etc")
    # and other injection attempts.
    if not _is_valid_report_id(report_id):
        return (
            jsonify({
                "error": "Invalid report ID format",
            }),
            400,
        )

    # ── Step 2: Load the report from disk ────────────────────
    try:
        found, report_data = file_handler.load_report(
            report_id
        )
    except Exception:
        # Defensive: catch any unexpected filesystem errors
        return (
            jsonify({
                "error": "Report retrieval failed",
                "report_id": report_id,
            }),
            500,
        )

    # ── Step 3: Return report or 404 ─────────────────────────
    if not found:
        return (
            jsonify({
                "error": "Report not found",
                "report_id": report_id,
            }),
            404,
        )

    return jsonify(report_data), 200
