# ============================================================
# forensics/font_inspector.py — AuthentIfy Backend
# Project: AuthentIfy — "Verify before you trust."
# Role   : Inspects PDF font metadata to detect typography
#          anomalies that indicate document tampering.
#
# ── Why Fonts Reveal Tampering ─────────────────────────────
# Official government documents (Aadhaar, PAN, marksheets,
# transcripts) are generated by specific enterprise software
# that embeds specific fonts in a predictable, consistent way.
#
# When someone tampers with a PDF using a consumer editor:
#   • New fonts are introduced that were not present in the
#     original (e.g., Courier injected into a NotoSans doc).
#   • The same page ends up with an unusual mix of font
#     families — genuine gov docs rarely use more than 3–4.
#   • Fonts may be referenced but NOT embedded.  The PDF
#     spec defines font flags (stored as a bitmask) that
#     reveal embedding status:
#       - Flag bit 2 (value 4) = "Nonsymbolic" / not embedded
#         in some implementations.  More reliably, fonts
#         whose "file" entry is absent from the font
#         descriptor are externally referenced — suspicious
#         for official documents that should be self-contained.
#   • Symbol fonts (ZapfDingbats, Wingdings, Webdings) have
#     no place in a text-based government document.
#   • Known editing-artifact fonts (Courier, Comic Sans,
#     Impact) signal manual re-creation or alteration.
#
# This module extracts font data from every page of a PDF,
# analyzes font diversity, checks against a blacklist, and
# detects cross-page inconsistencies that betray tampering.
#
# This is a PURE ALGORITHM FILE — no Flask, no Config,
# no file I/O, no scoring.
#
# Called by: services/metadata_analyzer.py
# Input   : fitz.Document object
# Output  : Dict with font findings and issues
# ============================================================

from __future__ import annotations

import fitz  # PyMuPDF


# ── Default Suspicious Font Blacklist ────────────────────────
# Fonts that should NOT appear in genuine government or
# institutional documents.  Matched case-insensitively as
# substrings against extracted font names.

_DEFAULT_SUSPICIOUS_FONTS: list[str] = [
    "courier",       # Typewriter font — common in forgeries
    "comic sans",    # Novelty font — never used officially
    "wingdings",     # Symbol/dingbat font — not text content
    "zapfdingbats",  # PDF built-in symbol font
    "symbol",        # Math/symbol font — suspicious in text
    "webdings",      # Web symbol font — no place in docs
    "impact",        # Display font — suggests manual editing
]

# ── Thresholds ───────────────────────────────────────────────

# Maximum distinct font families expected on a single page
# of a genuine government document.  Official generators
# typically use 1–3 fonts (heading, body, maybe monospace
# for codes).  More than this suggests manual composition.
_MAX_FONTS_PER_PAGE = 4


def inspect_fonts(
    doc: fitz.Document,
    suspicious_font_names: list[str] | None = None,
) -> dict:
    """Inspect all fonts in a PDF for tampering indicators.

    Examines font embedding metadata across every page to
    detect anomalies that betray document manipulation.

    PDF Font Flags (from the PDF specification):
        Fonts in a PDF carry a "flags" bitmask in their font
        descriptor that encodes properties like:
          Bit 0 (1)   — FixedPitch (monospaced)
          Bit 1 (2)   — Serif
          Bit 2 (4)   — Symbolic (uses Symbol encoding)
          Bit 5 (32)  — Nonsymbolic (uses standard encoding)
          Bit 6 (64)  — Italic
        The embedding status is determined by whether the
        font descriptor contains an embedded font stream
        ("file", "file2", or "file3" entries).  When a font
        is not embedded, the PDF viewer must substitute a
        system font — this means the document's appearance
        is not self-contained, which is atypical for official
        documents.

    Checks performed:
        1. Excessive font diversity on a single page (> 4).
        2. Presence of blacklisted / suspicious font names.
        3. Non-embedded fonts (externally referenced).
        4. Cross-page font inconsistency (drastically
           different font sets between pages).

    Args:
        doc: An open fitz.Document (PyMuPDF).
        suspicious_font_names: Optional list of font name
            substrings to flag (case-insensitive).  If None,
            uses the built-in default blacklist.

    Returns:
        dict with keys:
            fonts_found              (list[str])  — All unique
                font basenames found in the document.
            fonts_per_page           (list[int])  — Count of
                distinct fonts on each page.
            suspicious_fonts         (list[str])  — Font names
                that matched the blacklist.
            non_embedded_fonts       (list[str])  — Font names
                that are not embedded in the PDF.
            cross_page_inconsistency (bool)       — True if
                font sets vary dramatically between pages.
            issues                   (list[str])  — Human-
                readable issue descriptions for the frontend.
            error                    (None|str)   — Error
                description on failure; None on success.
    """
    # ── Fallback blacklist ───────────────────────────────────
    if suspicious_font_names is None:
        suspicious_font_names = _DEFAULT_SUSPICIOUS_FONTS

    # ── Safe default return ──────────────────────────────────
    default_result: dict = {
        "fonts_found": [],
        "fonts_per_page": [],
        "suspicious_fonts": [],
        "non_embedded_fonts": [],
        "cross_page_inconsistency": False,
        "issues": [],
        "error": None,
    }

    try:
        page_count = len(doc)
        if page_count == 0:
            default_result["error"] = "Document has no pages."
            return default_result

        # ── Collect font data from every page ────────────────
        # fitz page.get_fonts() returns a list of tuples:
        #   (xref, ext, type, basefont, name, encoding)
        # Index 3 = basefont (the font's PostScript name)
        # Index 4 = name (internal reference name)
        # Index 2 = type (e.g., "Type1", "TrueType", "CIDFontType0")

        all_font_names: set[str] = set()
        fonts_per_page: list[int] = []
        per_page_font_sets: list[set[str]] = []
        non_embedded: set[str] = set()

        for page_idx in range(page_count):
            page = doc[page_idx]

            # full=True returns extended info including
            # embedding status
            page_fonts = page.get_fonts(full=True)

            page_font_names: set[str] = set()

            for font_entry in page_fonts:
                # Extract the basefont name (index 3) or
                # fall back to internal name (index 4)
                basefont = (
                    font_entry[3]
                    if len(font_entry) > 3 and font_entry[3]
                    else ""
                )
                name = (
                    font_entry[4]
                    if len(font_entry) > 4 and font_entry[4]
                    else ""
                )

                # Use basefont preferentially; fall back to name
                font_label = basefont or name or "Unknown"

                # Strip subset prefix (e.g., "ABCDEF+Arial"
                # → "Arial").  PDF subsetted fonts use a
                # 6-letter uppercase prefix followed by "+".
                if "+" in font_label:
                    font_label = font_label.split("+", 1)[1]

                page_font_names.add(font_label)
                all_font_names.add(font_label)

                # ── Check embedding status ───────────────────
                # In PyMuPDF's full font list, index 2 is the
                # font type.  If the type string contains
                # "Type3" the font is defined inline.  For
                # other types, we check if the xref (index 0)
                # points to an embedded stream.
                font_type = (
                    font_entry[2]
                    if len(font_entry) > 2 and font_entry[2]
                    else ""
                )
                xref = (
                    font_entry[0]
                    if len(font_entry) > 0
                    else 0
                )

                # A font with xref=0 or an empty/missing
                # encoding (index 5) often indicates it is
                # not properly embedded.
                encoding = (
                    font_entry[5]
                    if len(font_entry) > 5 and font_entry[5]
                    else ""
                )

                # Heuristic: if encoding is empty and font
                # type is not Type3 (inline), treat as
                # potentially non-embedded.  Also, "Type1"
                # fonts without embedding streams are
                # externally referenced.
                if (
                    not encoding
                    and font_type != "Type3"
                    and xref == 0
                ):
                    non_embedded.add(font_label)

            # Record per-page counts and sets
            fonts_per_page.append(len(page_font_names))
            per_page_font_sets.append(page_font_names)

        # ── Build sorted lists for output ────────────────────
        sorted_fonts = sorted(all_font_names)
        sorted_non_embedded = sorted(non_embedded)

        # ── Check 1: Excessive fonts per page ────────────────
        issues: list[str] = []

        for page_idx, count in enumerate(fonts_per_page):
            if count > _MAX_FONTS_PER_PAGE:
                issues.append(
                    f"Page {page_idx + 1} uses {count} "
                    f"distinct fonts — genuine documents "
                    f"rarely exceed {_MAX_FONTS_PER_PAGE}."
                )

        # ── Check 2: Suspicious font names ───────────────────
        matched_suspicious: list[str] = []

        for font_name in sorted_fonts:
            font_lower = font_name.lower()
            for suspect in suspicious_font_names:
                if suspect.lower() in font_lower:
                    matched_suspicious.append(font_name)
                    break  # one match per font is enough

        if matched_suspicious:
            names_str = ", ".join(matched_suspicious)
            issues.append(
                f"Suspicious font(s) detected: {names_str}. "
                f"These are not typically found in official "
                f"government or institutional documents."
            )

        # ── Check 3: Non-embedded fonts ──────────────────────
        if sorted_non_embedded:
            names_str = ", ".join(sorted_non_embedded)
            issues.append(
                f"Non-embedded font(s) found: {names_str}. "
                f"Official documents typically embed all "
                f"fonts to ensure consistent rendering."
            )

        # ── Check 4: Cross-page font inconsistency ───────────
        cross_page_flag = _check_cross_page_inconsistency(
            per_page_font_sets
        )

        if cross_page_flag:
            issues.append(
                "Font usage varies significantly between "
                "pages — this may indicate pages were "
                "sourced from different documents."
            )

        return {
            "fonts_found": sorted_fonts,
            "fonts_per_page": fonts_per_page,
            "suspicious_fonts": matched_suspicious,
            "non_embedded_fonts": sorted_non_embedded,
            "cross_page_inconsistency": cross_page_flag,
            "issues": issues,
            "error": None,
        }

    except Exception as exc:
        # Never crash — return safe default with error detail
        return {
            "fonts_found": [],
            "fonts_per_page": [],
            "suspicious_fonts": [],
            "non_embedded_fonts": [],
            "cross_page_inconsistency": False,
            "issues": [],
            "error": f"Font inspection failed: {exc}",
        }


# ── Internal Helpers ─────────────────────────────────────────


def _check_cross_page_inconsistency(
    per_page_font_sets: list[set[str]],
) -> bool:
    """Detect if font usage varies drastically between pages.

    Compares every pair of adjacent pages.  If any page
    introduces more than 2 fonts not present on its neighbor,
    the document is flagged as inconsistent.

    For single-page documents, returns False (nothing to
    compare).

    Rationale:
        A genuine multi-page document produced by a single
        generator will use the same font set (or very close)
        on every page.  If page 1 uses only "Arial" and
        page 2 suddenly introduces "Arial + Courier +
        Unknown", it suggests page 2 was created separately.

    Args:
        per_page_font_sets: List of sets, one per page,
            containing the font names used on that page.

    Returns:
        True if significant font inconsistency is detected.
    """
    if len(per_page_font_sets) < 2:
        return False

    for i in range(len(per_page_font_sets) - 1):
        current_page = per_page_font_sets[i]
        next_page = per_page_font_sets[i + 1]

        # Fonts in next page but not in current page
        new_fonts = next_page - current_page

        # If a page introduces more than 2 entirely new font
        # families compared to the previous page, flag it.
        if len(new_fonts) > 2:
            return True

    # Also check if the overall font diversity across all
    # pages is suspiciously high compared to any single page.
    # If the union of all page fonts is more than double the
    # average per-page count, something is off.
    all_fonts = set()
    total_per_page = 0

    for page_set in per_page_font_sets:
        all_fonts.update(page_set)
        total_per_page += len(page_set)

    avg_per_page = total_per_page / len(per_page_font_sets)

    # If overall unique fonts are more than double the average
    # page count and there are at least 4 unique fonts total,
    # flag as inconsistent.
    if len(all_fonts) > avg_per_page * 2 and len(all_fonts) >= 4:
        return True

    return False
